# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('profil_id', models.AutoField(primary_key=True, serialize=False)),
                ('profil_judul', models.CharField(max_length=200)),
                ('profil_isi', models.TextField()),
            ],
        ),
    ]
