# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
