# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('profil_id', models.AutoField(primary_key=True, serialize=False)),
                ('profil_nama', models.CharField(max_length=50)),
                ('profil_alias', models.CharField(max_length=50)),
                ('profil_alamat', models.TextField()),
                ('profil_tlp', models.IntegerField()),
            ],
        ),
    ]
