# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_authid', models.IntegerField()),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_status', models.IntegerField()),
                ('log_action', models.TextField()),
            ],
        ),
    ]
