# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_remove_login_log_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_log',
            name='log_session',
            field=models.TextField(blank=True, null=True),
        ),
    ]
